package com.milesgwood.moe.hbm;
// Generated Feb 20, 2017 1:21:36 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 * Songs generated by hbm2java
 */
public class Songs  implements java.io.Serializable {

     private Integer id;
     private Integer showId;
     private String name;
     private String mtime;
     private String source;
     private String format;
     private String length;
     private String track;
     private String title;
     private String album;
     private Integer score;
     //The show attribute allows you to map from a song to it's parent show
     private Shows show;

    public Songs() {
    }

	
    public Songs(String name) {
        this.name = name;
    }
    public Songs(Integer showId, String name, String mtime, String source, String format, String length, String track, String title, String album, Integer score) {
       this.showId = showId;
       this.name = name;
       this.mtime = mtime;
       this.source = source;
       this.format = format;
       this.length = length;
       this.track = track;
       this.title = title;
       this.album = album;
       this.score = score;
    }
    
    public Shows getShow() {
        return show;
    }

    public void setShow(Shows show) {
        this.show = show;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getShowId() {
        return this.showId;
    }
    
    public void setShowId(Integer showId) {
        this.showId = showId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMtime() {
        return this.mtime;
    }
    
    public void setMtime(String mtime) {
        this.mtime = mtime;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getLength() {
        return this.length;
    }
    
    public void setLength(String length) {
        this.length = length;
    }
    public String getTrack() {
        return this.track;
    }
    
    public void setTrack(String track) {
        this.track = track;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }
    
    /**
     * This method converts the Songs object into JSON format to get sent in a HTTP response.
     * @return 
     */
    public String toJSON() {
        String jsonInString = "Something went horribly wrong when I tried to get that Song and turn it into JSON. I'm drunk. Leave me alone and go listen to something else other than song ID: " + this.id;
        String errorMessage = jsonInString;
        ObjectMapper mapper = new ObjectMapper();
         try {
             jsonInString = mapper.writeValueAsString(this);
         } catch (JsonProcessingException ex) {
             Logger.getLogger(Shows.class.getName()).log(Level.SEVERE, errorMessage, ex);
         }
        return jsonInString;
    }
}


